
   [ 
        {
            id:1,
            brand:"Dell",
            price:39999,
            img:"https://m.media-amazon.com/images/I/61q6x-ll5FL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4,
            catergory:"Laptop"
        },
        {
            id:2,
            brand:"hp",
            price:35999,
            img:"https://m.media-amazon.com/images/I/61FTtuGY8iL._AC_UL480_FMwebp_QL65_.jpg",
            rating:4,
            catergory:"Laptop"
        },
        {
            id:3,
            brand:"Asus",
            price:42990,
            img:"https://m.media-amazon.com/images/I/71veuBka4NL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4,
            catergory:"Laptop"
        },
        {
            id:4,
            brand:"Apple",
            price:109999,
            img:"https://m.media-amazon.com/images/I/71f5Eu5lJSL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4,
            catergory:"Laptop"
        },
        {
            id:5,
            brand:"Samsung",
            price:45999,
            img:"https://m.media-amazon.com/images/I/61wqYsqU6AL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4,
            catergory:"Laptop"
        },
        {
            id:6,
            brand:"Infinix",
            price:32999,      
            img:"https://m.media-amazon.com/images/I/61Dw5Z8LzJL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4,
            catergory:"Laptop"
        },
        {
            id:7,
            brand:"Msi",
            price:48999,
            img:"https://m.media-amazon.com/images/I/61U9L2s5bDL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4,
            catergory:"Laptop"
        },
        {
            id:8,
            brand:"Lenovo",
            price:48000,
            img:"https://m.media-amazon.com/images/I/71GF48DOZhL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4,
            catergory:"Laptop"
        },
        {
            id:9,
            brand:"Razer",
            price:36999,
            img:"https://m.media-amazon.com/images/I/71w0hh-Q4aL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4,
            catergory:"Laptop"
        },
        {
            id:10,
            brand:"Toshiba",
            price:36999,
            img:"https://m.media-amazon.com/images/I/418xqhxMCHL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4,
            catergory:"Laptop"
        },
        {
            id:11,
            brand:"Toshiba",
            price:3999,
            img:"https://m.media-amazon.com/images/I/51xxA+6E+xL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4.5,
            catergory:"Headphone"
        },
        {
            id:12,
            brand:"Dell",
            price:2599,
            img:"https://m.media-amazon.com/images/I/418xqhxMCHL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4.5,
            catergory:"Headphone"
        },
        {
            id:13,
            brand:"hp",
            price:2899,
            img:"https://m.media-amazon.com/images/I/61kWB+uzR2L._AC_UY327_FMwebp_QL65_.jpg",
            rating:4.5,
            catergory:"Headphone"
        },
        {
            id:14,
            brand:"Boat",
            price:2366,
            img:"https://m.media-amazon.com/images/I/71HbypECPYL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4.5,
            catergory:"Headphone"
        },
        {
            id:15,
            brand:"Zebronics",
            price:4200,
            img:"https://m.media-amazon.com/images/I/418xqhxMCHL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4.5,
            catergory:"Headphone"
        },
        {
            id:16,
            brand:" oneplus",
            price:2300,
            img:"https://m.media-amazon.com/images/I/71fvr5CC+aL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4.5,
            catergory:"Headphone"
        },
        {
            id:17,
            brand:"JBL",
            price:1899,
            img:"https://m.media-amazon.com/images/I/61Pe1nFYrFL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4.5,
            catergory:"Headphone"
        },
        {
            id:18,
            brand:"Noise",
            price:5600,
            img:"https://m.media-amazon.com/images/I/61iK8fdAa+S._AC_UY327_FMwebp_QL65_.jpg",
            rating:4.5,
            catergory:"Headphone"
        },
        {
            id:19,
            brand:"Realme",
            price:4500,
            img:"https://m.media-amazon.com/images/I/51Y7SIK68KL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4.5,
            catergory:"Headphone"
        },
        {
            id:20,
            brand:"Boult",
            price:1599,
            img:"https://m.media-amazon.com/images/I/817WP7J8ZOL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4.5,
            catergory:"Headphone"
        },
        {
            id:21,
            brand:"Toshiba",
            price:2599,
            img:"https://m.media-amazon.com/images/I/71MP6Tse68L._AC_UY327_FMwebp_QL65_.jpg",
            rating:4.5,
            catergory:"Watch"
        },
        {
            id:22,
            brand:"Boat",
            price:1718,
            img:"https://m.media-amazon.com/images/I/61IMRs+o0iL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4.5,
            catergory:"Watch"
        },
        {
            id:23,
            brand:"Realme",
            price:2999,
            img:"https://m.media-amazon.com/images/I/614SBqXrTES._AC_UY327_FMwebp_QL65_.jpg",
            rating:4.5,
            catergory:"Watch"
        },
        {
            id:24,
            brand:"Noise",
            price:2899,
            img:"",
            rating:4.5,
            catergory:"Watch"
        },
        {
            id:25,
            brand:"Apple",
            price:23000,
            img:"https://m.media-amazon.com/images/I/71+FrNJ61dL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4.5,
            catergory:"Watch"
        },
        {
            id:26,
            brand:"Casio",
            price:1999,
            img:"https://m.media-amazon.com/images/I/61mRKaLJg2L._AC_UL480_FMwebp_QL65_.jpg",
            rating:4.5,
            catergory:"Watch"
        },
        {
            id:27,
            brand:"Patek Philippe",
            price:4599,
            img:"https://m.media-amazon.com/images/I/61y2VVWcGBL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4.5,
            catergory:"Watch"
        },
        {
            id:28,
            brand:"Fitbit",
            price:1499,
            img:"https://m.media-amazon.com/images/I/712VGfMEouL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4.5,
            catergory:"Watch"
        },
        {
            id:29,
            brand:"Fossil",
            price:1299,
            img:"https://m.media-amazon.com/images/I/618mFEP9mTL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4.5,
            catergory:"Watch"
        },
        {
            id:30,
            brand:"Amazfit",
            price:2199,
            img:"https://m.media-amazon.com/images/I/61kyPt4PQFL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4.5,
            catergory:"Watch"
        },
        {
            id:11,
            brand:"Toshiba",
            price:3999,
            img:"https://m.media-amazon.com/images/I/418xqhxMCHL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4.5,
            catergory:"Watch"
        },
        {
            id:11,
            brand:"Toshiba",
            price:3999,
            img:"https://m.media-amazon.com/images/I/418xqhxMCHL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4.5,
            catergory:"Watch"
        },
        {
            id:11,
            brand:"Toshiba",
            price:3999,
            img:"https://m.media-amazon.com/images/I/418xqhxMCHL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4.5,
            catergory:"Watch"
        },
        {
            id:11,
            brand:"Toshiba",
            price:3999,
            img:"https://m.media-amazon.com/images/I/418xqhxMCHL._AC_UY327_FMwebp_QL65_.jpg",
            rating:4.5,
            catergory:"Watch"
        },
        


   ]
